name = "cf_ws"
main = "build/worker/shim.mjs"
compatibility_date = "2024-12-20"

[build]
command = "cargo install -q worker-build && worker-build --release"

[durable_objects]
bindings = [
  { name = "USER_DATA_WRAPPER", class_name = "UserDataWrapper" },
]

[triggers]
crons = ["*/10 * * * *"]

[[migrations]]
tag = "v1"
new_classes = [ "UserDataWrapper" ]

[observability.logs]
enabled = true

[[d1_databases]]
binding = "D1_DATABASE"
database_name = "d1_database"
database_id = "d1_database"

[vars]
GPT_CLIENT_SECRET = "your-secret-here"