name = "cf_ws"
main = "build/worker/shim.mjs"
compatibility_date = "2024-03-20"

[build]
command = "cargo install -q worker-build && worker-build --release"


[durable_objects]
bindings = [
  { name = "USER_DATA_WRAPPER", class_name = "UserDataWrapper" },
]

[[migrations]]
tag = "v1"
new_classes = [ "UserDataWrapper" ]

[observability.logs]
enabled = true

[[d1_databases]]
binding = "D1_DATABASE"
database_name = "game-data"
database_id = "249c88d3-d81c-48a3-b4de-d56c42214e4a"